#pragma once

#include <cmath>
#include <random>
#include <utility>


// std::pow(x, n) is slow because of its overkill-level precision. Profiling
// showed that this implementation is faster for small n.
inline double
small_pow(double x, unsigned n)
{
    if (n == 0) [[likely]] {
        return 1;
    }
    double y = x;
    for (unsigned i = 1; i < n; i++) {
        y *= x;
    }
    return y;
}


// Approximates `1 - exp(-x)` at the fourth-order accuracy for small |x|.
//
// We need this fast approximation because a profiling showed that
// association_simulator consumes significant amount of time calculating
// Poisson process probability values.
inline double
neg_exp(double x)
{
    if (std::fabs(x) > 1) [[unlikely]] {
        return -std::expm1(-x);
    }
    auto const x2_div2 = (x * x) * (1.0 / 2);
    auto const x3_div6 = (x2_div2 * x) * (1.0 / 3);
    auto const x4_div24 = (x2_div2 * x2_div2) * (1.0 / 6);
    return x - x2_div2 + x3_div6 - x4_div24;
}


// Returns true in the given probability.
template<typename RNG>
bool
random_branch(double p, RNG& random)
{
    // Simple `random() < threshold` or std::bernoulli_distribution(p)
    // effectively tests the highest bits of an integer generated by PRNG.
    // That method seems to produce correlations with other random number
    // generations in a simulation. In our tests, the bias could be found
    // even with high-quality PRNGs like PCG64 depending on a seed,
    // significantly affecting simulation results. Here, we use two random
    // numbers, which circumvents the correlation issue.
    std::uniform_real_distribution<double> uniform;
    return uniform(random) < 2 * p * uniform(random);
}


// Returns true in 50% probability.
template<typename RNG>
bool
random_branch(RNG& random)
{
    return random_branch(0.5, random);
}


// Swaps x and y in 50% probability.
template<typename T, typename RNG>
void
random_swap(T& x, T& y, RNG& random)
{
    if (random_branch(0.5, random)) {
        std::swap(x, y);
    }
}


// Simulates a Poisson process event in given time interval. Returns true if
// at least one event occurs, or false otherwise.
template<typename RNG>
bool
poisson_process(double rate, double dt, RNG& random)
{
    return random_branch(neg_exp(rate * dt), random);
}


// Calculates the harmonic composition of two rates.
inline double
harmonic_rate(double rate_1, double rate_2, double epsilon = 1e-8)
{
    return rate_1 * rate_2 / (rate_1 + rate_2 + epsilon);
}
